package foundation.odin.parsing;

public enum TokenType {
    Path,
    Equals,
    QuotedString,
    BareWord,
    NumberPrefix,
    IntegerPrefix,
    CurrencyPrefix,
    PercentPrefix,
    BooleanPrefix,
    Null,
    ReferencePrefix,
    BinaryPrefix,
    VerbPrefix,
    Header,
    Comment,
    Directive,
    Import,
    Schema,
    Newline,
    Eof,
    NumericLiteral,
    BooleanLiteral,
    DateLiteral,
    TimestampLiteral,
    TimeLiteral,
    DurationLiteral,
    Modifier,
    Pipe,
    DocumentSeparator,
    Conditional,
    Comma
}
